#!/usr/bin/env php
<?php

if (isset($GLOBALS['_composer_autoload_path'])) {
    require_once $GLOBALS['_composer_autoload_path'];

    unset($GLOBALS['_composer_autoload_path']);
} else {
    foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
        if (file_exists($file)) {
            require_once $file;

            break;
        }
    }

    unset($file);
}

use Killposer\Commands\ScanCommand;
use Symfony\Component\Console\Application;

$app = new Application('killposer', '1.0.0');
$app->addCommand(new ScanCommand());
$app->setDefaultCommand('scan', true);
$app->run();
